// Code generated by fm-token-gen; DO NOT EDIT.

package tokenid

const (
	TK_EOF                                  = 0
	TK_BLANK                                = 1
	TK_START_TAG                            = 2
	TK_END_TAG                              = 3
	TK_CLOSE_TAG1                           = 4
	TK_CLOSE_TAG2                           = 5
	TK_ATTEMPT                              = 6
	TK_RECOVER                              = 7
	TK_IF                                   = 8
	TK_ELSE_IF                              = 9
	TK_LIST                                 = 10
	TK_ITEMS                                = 11
	TK_SEP                                  = 12
	TK_FOREACH                              = 13
	TK_SWITCH                               = 14
	TK_CASE                                 = 15
	TK_ON                                   = 16
	TK_ASSIGN                               = 17
	TK_GLOBALASSIGN                         = 18
	TK_LOCALASSIGN                          = 19
	TK__INCLUDE                             = 20
	TK_IMPORT                               = 21
	TK_FUNCTION                             = 22
	TK_MACRO                                = 23
	TK_TRANSFORM                            = 24
	TK_VISIT                                = 25
	TK_STOP                                 = 26
	TK_RETURN                               = 27
	TK_CALL                                 = 28
	TK_SETTING                              = 29
	TK_OUTPUTFORMAT                         = 30
	TK_AUTOESC                              = 31
	TK_NOAUTOESC                            = 32
	TK_COMPRESS                             = 33
	TK_COMMENT                              = 34
	TK_TERSE_COMMENT                        = 35
	TK_NOPARSE                              = 36
	TK_END_IF                               = 37
	TK_END_LIST                             = 38
	TK_END_ITEMS                            = 39
	TK_END_SEP                              = 40
	TK_END_RECOVER                          = 41
	TK_END_ATTEMPT                          = 42
	TK_END_FOREACH                          = 43
	TK_END_LOCAL                            = 44
	TK_END_GLOBAL                           = 45
	TK_END_ASSIGN                           = 46
	TK_END_FUNCTION                         = 47
	TK_END_MACRO                            = 48
	TK_END_OUTPUTFORMAT                     = 49
	TK_END_AUTOESC                          = 50
	TK_END_NOAUTOESC                        = 51
	TK_END_COMPRESS                         = 52
	TK_END_TRANSFORM                        = 53
	TK_END_SWITCH                           = 54
	TK_ELSE                                 = 55
	TK_BREAK                                = 56
	TK_CONTINUE                             = 57
	TK_SIMPLE_RETURN                        = 58
	TK_HALT                                 = 59
	TK_FLUSH                                = 60
	TK_TRIM                                 = 61
	TK_LTRIM                                = 62
	TK_RTRIM                                = 63
	TK_NOTRIM                               = 64
	TK_DEFAUL                               = 65
	TK_SIMPLE_NESTED                        = 66
	TK_NESTED                               = 67
	TK_SIMPLE_RECURSE                       = 68
	TK_RECURSE                              = 69
	TK_FALLBACK                             = 70
	TK_ESCAPE                               = 71
	TK_END_ESCAPE                           = 72
	TK_NOESCAPE                             = 73
	TK_END_NOESCAPE                         = 74
	TK_UNIFIED_CALL                         = 75
	TK_UNIFIED_CALL_END                     = 76
	TK_FTL_HEADER                           = 77
	TK_TRIVIAL_FTL_HEADER                   = 78
	TK_UNKNOWN_DIRECTIVE                    = 79
	TK_STATIC_TEXT_WS                       = 80
	TK_STATIC_TEXT_NON_WS                   = 81
	TK_STATIC_TEXT_FALSE_ALARM              = 82
	TK_DOLLAR_INTERPOLATION_OPENING         = 83
	TK_HASH_INTERPOLATION_OPENING           = 84
	TK_SQUARE_BRACKET_INTERPOLATION_OPENING = 85
	TK_ESCAPED_CHAR                         = 86
	TK_STRING_LITERAL                       = 87
	TK_RAW_STRING                           = 88
	TK_FALSE                                = 89
	TK_TRUE                                 = 90
	TK_INTEGER                              = 91
	TK_DECIMAL                              = 92
	TK_DOT                                  = 93
	TK_DOT_DOT                              = 94
	TK_DOT_DOT_LESS                         = 95
	TK_DOT_DOT_ASTERISK                     = 96
	TK_BUILT_IN                             = 97
	TK_EXISTS                               = 98
	TK_EQUALS                               = 99
	TK_DOUBLE_EQUALS                        = 100
	TK_NOT_EQUALS                           = 101
	TK_PLUS_EQUALS                          = 102
	TK_MINUS_EQUALS                         = 103
	TK_TIMES_EQUALS                         = 104
	TK_DIV_EQUALS                           = 105
	TK_MOD_EQUALS                           = 106
	TK_PLUS_PLUS                            = 107
	TK_MINUS_MINUS                          = 108
	TK_LESS_THAN                            = 109
	TK_LESS_THAN_EQUALS                     = 110
	TK_ESCAPED_GT                           = 111
	TK_ESCAPED_GTE                          = 112
	TK_LAMBDA_ARROW                         = 113
	TK_PLUS                                 = 114
	TK_MINUS                                = 115
	TK_TIMES                                = 116
	TK_DOUBLE_STAR                          = 117
	TK_ELLIPSIS                             = 118
	TK_DIVIDE                               = 119
	TK_PERCENT                              = 120
	TK_AND                                  = 121
	TK_OR                                   = 122
	TK_EXCLAM                               = 123
	TK_COMMA                                = 124
	TK_SEMICOLON                            = 125
	TK_COLON                                = 126
	TK_OPEN_BRACKET                         = 127
	TK_CLOSE_BRACKET                        = 128
	TK_OPEN_PAREN                           = 129
	TK_CLOSE_PAREN                          = 130
	TK_OPENING_CURLY_BRACKET                = 131
	TK_CLOSING_CURLY_BRACKET                = 132
	TK_IN                                   = 133
	TK_AS                                   = 134
	TK_USING                                = 135
	TK_ID                                   = 136
	TK_OPEN_MISPLACED_INTERPOLATION         = 137
	TK_NON_ESCAPED_ID_START_CHAR            = 138
	TK_ESCAPED_ID_CHAR                      = 139
	TK_ID_START_CHAR                        = 140
	TK_ASCII_DIGIT                          = 141
	TK_DIRECTIVE_END                        = 142
	TK_EMPTY_DIRECTIVE_END                  = 143
	TK_NATURAL_GT                           = 144
	TK_NATURAL_GTE                          = 145
	TK_TERMINATING_WHITESPACE               = 146
	TK_TERMINATING_EXCLAM                   = 147
	TK_TERSE_COMMENT_END                    = 148
	TK_MAYBE_END                            = 149
	TK_KEEP_GOING                           = 150
	TK_LONE_LESS_THAN_OR_DASH               = 151
)

var IDToName = map[int]string{
	0:   "EOF",
	1:   "BLANK",
	2:   "START_TAG",
	3:   "END_TAG",
	4:   "CLOSE_TAG1",
	5:   "CLOSE_TAG2",
	6:   "ATTEMPT",
	7:   "RECOVER",
	8:   "IF",
	9:   "ELSE_IF",
	10:  "LIST",
	11:  "ITEMS",
	12:  "SEP",
	13:  "FOREACH",
	14:  "SWITCH",
	15:  "CASE",
	16:  "ON",
	17:  "ASSIGN",
	18:  "GLOBALASSIGN",
	19:  "LOCALASSIGN",
	20:  "_INCLUDE",
	21:  "IMPORT",
	22:  "FUNCTION",
	23:  "MACRO",
	24:  "TRANSFORM",
	25:  "VISIT",
	26:  "STOP",
	27:  "RETURN",
	28:  "CALL",
	29:  "SETTING",
	30:  "OUTPUTFORMAT",
	31:  "AUTOESC",
	32:  "NOAUTOESC",
	33:  "COMPRESS",
	34:  "COMMENT",
	35:  "TERSE_COMMENT",
	36:  "NOPARSE",
	37:  "END_IF",
	38:  "END_LIST",
	39:  "END_ITEMS",
	40:  "END_SEP",
	41:  "END_RECOVER",
	42:  "END_ATTEMPT",
	43:  "END_FOREACH",
	44:  "END_LOCAL",
	45:  "END_GLOBAL",
	46:  "END_ASSIGN",
	47:  "END_FUNCTION",
	48:  "END_MACRO",
	49:  "END_OUTPUTFORMAT",
	50:  "END_AUTOESC",
	51:  "END_NOAUTOESC",
	52:  "END_COMPRESS",
	53:  "END_TRANSFORM",
	54:  "END_SWITCH",
	55:  "ELSE",
	56:  "BREAK",
	57:  "CONTINUE",
	58:  "SIMPLE_RETURN",
	59:  "HALT",
	60:  "FLUSH",
	61:  "TRIM",
	62:  "LTRIM",
	63:  "RTRIM",
	64:  "NOTRIM",
	65:  "DEFAUL",
	66:  "SIMPLE_NESTED",
	67:  "NESTED",
	68:  "SIMPLE_RECURSE",
	69:  "RECURSE",
	70:  "FALLBACK",
	71:  "ESCAPE",
	72:  "END_ESCAPE",
	73:  "NOESCAPE",
	74:  "END_NOESCAPE",
	75:  "UNIFIED_CALL",
	76:  "UNIFIED_CALL_END",
	77:  "FTL_HEADER",
	78:  "TRIVIAL_FTL_HEADER",
	79:  "UNKNOWN_DIRECTIVE",
	80:  "STATIC_TEXT_WS",
	81:  "STATIC_TEXT_NON_WS",
	82:  "STATIC_TEXT_FALSE_ALARM",
	83:  "DOLLAR_INTERPOLATION_OPENING",
	84:  "HASH_INTERPOLATION_OPENING",
	85:  "SQUARE_BRACKET_INTERPOLATION_OPENING",
	86:  "ESCAPED_CHAR",
	87:  "STRING_LITERAL",
	88:  "RAW_STRING",
	89:  "FALSE",
	90:  "TRUE",
	91:  "INTEGER",
	92:  "DECIMAL",
	93:  "DOT",
	94:  "DOT_DOT",
	95:  "DOT_DOT_LESS",
	96:  "DOT_DOT_ASTERISK",
	97:  "BUILT_IN",
	98:  "EXISTS",
	99:  "EQUALS",
	100: "DOUBLE_EQUALS",
	101: "NOT_EQUALS",
	102: "PLUS_EQUALS",
	103: "MINUS_EQUALS",
	104: "TIMES_EQUALS",
	105: "DIV_EQUALS",
	106: "MOD_EQUALS",
	107: "PLUS_PLUS",
	108: "MINUS_MINUS",
	109: "LESS_THAN",
	110: "LESS_THAN_EQUALS",
	111: "ESCAPED_GT",
	112: "ESCAPED_GTE",
	113: "LAMBDA_ARROW",
	114: "PLUS",
	115: "MINUS",
	116: "TIMES",
	117: "DOUBLE_STAR",
	118: "ELLIPSIS",
	119: "DIVIDE",
	120: "PERCENT",
	121: "AND",
	122: "OR",
	123: "EXCLAM",
	124: "COMMA",
	125: "SEMICOLON",
	126: "COLON",
	127: "OPEN_BRACKET",
	128: "CLOSE_BRACKET",
	129: "OPEN_PAREN",
	130: "CLOSE_PAREN",
	131: "OPENING_CURLY_BRACKET",
	132: "CLOSING_CURLY_BRACKET",
	133: "IN",
	134: "AS",
	135: "USING",
	136: "ID",
	137: "OPEN_MISPLACED_INTERPOLATION",
	138: "NON_ESCAPED_ID_START_CHAR",
	139: "ESCAPED_ID_CHAR",
	140: "ID_START_CHAR",
	141: "ASCII_DIGIT",
	142: "DIRECTIVE_END",
	143: "EMPTY_DIRECTIVE_END",
	144: "NATURAL_GT",
	145: "NATURAL_GTE",
	146: "TERMINATING_WHITESPACE",
	147: "TERMINATING_EXCLAM",
	148: "TERSE_COMMENT_END",
	149: "MAYBE_END",
	150: "KEEP_GOING",
	151: "LONE_LESS_THAN_OR_DASH",
}

var NameToID = map[string]int{
	"EOF":                                  0,
	"BLANK":                                1,
	"START_TAG":                            2,
	"END_TAG":                              3,
	"CLOSE_TAG1":                           4,
	"CLOSE_TAG2":                           5,
	"ATTEMPT":                              6,
	"RECOVER":                              7,
	"IF":                                   8,
	"ELSE_IF":                              9,
	"LIST":                                 10,
	"ITEMS":                                11,
	"SEP":                                  12,
	"FOREACH":                              13,
	"SWITCH":                               14,
	"CASE":                                 15,
	"ON":                                   16,
	"ASSIGN":                               17,
	"GLOBALASSIGN":                         18,
	"LOCALASSIGN":                          19,
	"_INCLUDE":                             20,
	"IMPORT":                               21,
	"FUNCTION":                             22,
	"MACRO":                                23,
	"TRANSFORM":                            24,
	"VISIT":                                25,
	"STOP":                                 26,
	"RETURN":                               27,
	"CALL":                                 28,
	"SETTING":                              29,
	"OUTPUTFORMAT":                         30,
	"AUTOESC":                              31,
	"NOAUTOESC":                            32,
	"COMPRESS":                             33,
	"COMMENT":                              34,
	"TERSE_COMMENT":                        35,
	"NOPARSE":                              36,
	"END_IF":                               37,
	"END_LIST":                             38,
	"END_ITEMS":                            39,
	"END_SEP":                              40,
	"END_RECOVER":                          41,
	"END_ATTEMPT":                          42,
	"END_FOREACH":                          43,
	"END_LOCAL":                            44,
	"END_GLOBAL":                           45,
	"END_ASSIGN":                           46,
	"END_FUNCTION":                         47,
	"END_MACRO":                            48,
	"END_OUTPUTFORMAT":                     49,
	"END_AUTOESC":                          50,
	"END_NOAUTOESC":                        51,
	"END_COMPRESS":                         52,
	"END_TRANSFORM":                        53,
	"END_SWITCH":                           54,
	"ELSE":                                 55,
	"BREAK":                                56,
	"CONTINUE":                             57,
	"SIMPLE_RETURN":                        58,
	"HALT":                                 59,
	"FLUSH":                                60,
	"TRIM":                                 61,
	"LTRIM":                                62,
	"RTRIM":                                63,
	"NOTRIM":                               64,
	"DEFAUL":                               65,
	"SIMPLE_NESTED":                        66,
	"NESTED":                               67,
	"SIMPLE_RECURSE":                       68,
	"RECURSE":                              69,
	"FALLBACK":                             70,
	"ESCAPE":                               71,
	"END_ESCAPE":                           72,
	"NOESCAPE":                             73,
	"END_NOESCAPE":                         74,
	"UNIFIED_CALL":                         75,
	"UNIFIED_CALL_END":                     76,
	"FTL_HEADER":                           77,
	"TRIVIAL_FTL_HEADER":                   78,
	"UNKNOWN_DIRECTIVE":                    79,
	"STATIC_TEXT_WS":                       80,
	"STATIC_TEXT_NON_WS":                   81,
	"STATIC_TEXT_FALSE_ALARM":              82,
	"DOLLAR_INTERPOLATION_OPENING":         83,
	"HASH_INTERPOLATION_OPENING":           84,
	"SQUARE_BRACKET_INTERPOLATION_OPENING": 85,
	"ESCAPED_CHAR":                         86,
	"STRING_LITERAL":                       87,
	"RAW_STRING":                           88,
	"FALSE":                                89,
	"TRUE":                                 90,
	"INTEGER":                              91,
	"DECIMAL":                              92,
	"DOT":                                  93,
	"DOT_DOT":                              94,
	"DOT_DOT_LESS":                         95,
	"DOT_DOT_ASTERISK":                     96,
	"BUILT_IN":                             97,
	"EXISTS":                               98,
	"EQUALS":                               99,
	"DOUBLE_EQUALS":                        100,
	"NOT_EQUALS":                           101,
	"PLUS_EQUALS":                          102,
	"MINUS_EQUALS":                         103,
	"TIMES_EQUALS":                         104,
	"DIV_EQUALS":                           105,
	"MOD_EQUALS":                           106,
	"PLUS_PLUS":                            107,
	"MINUS_MINUS":                          108,
	"LESS_THAN":                            109,
	"LESS_THAN_EQUALS":                     110,
	"ESCAPED_GT":                           111,
	"ESCAPED_GTE":                          112,
	"LAMBDA_ARROW":                         113,
	"PLUS":                                 114,
	"MINUS":                                115,
	"TIMES":                                116,
	"DOUBLE_STAR":                          117,
	"ELLIPSIS":                             118,
	"DIVIDE":                               119,
	"PERCENT":                              120,
	"AND":                                  121,
	"OR":                                   122,
	"EXCLAM":                               123,
	"COMMA":                                124,
	"SEMICOLON":                            125,
	"COLON":                                126,
	"OPEN_BRACKET":                         127,
	"CLOSE_BRACKET":                        128,
	"OPEN_PAREN":                           129,
	"CLOSE_PAREN":                          130,
	"OPENING_CURLY_BRACKET":                131,
	"CLOSING_CURLY_BRACKET":                132,
	"IN":                                   133,
	"AS":                                   134,
	"USING":                                135,
	"ID":                                   136,
	"OPEN_MISPLACED_INTERPOLATION":         137,
	"NON_ESCAPED_ID_START_CHAR":            138,
	"ESCAPED_ID_CHAR":                      139,
	"ID_START_CHAR":                        140,
	"ASCII_DIGIT":                          141,
	"DIRECTIVE_END":                        142,
	"EMPTY_DIRECTIVE_END":                  143,
	"NATURAL_GT":                           144,
	"NATURAL_GTE":                          145,
	"TERMINATING_WHITESPACE":               146,
	"TERMINATING_EXCLAM":                   147,
	"TERSE_COMMENT_END":                    148,
	"MAYBE_END":                            149,
	"KEEP_GOING":                           150,
	"LONE_LESS_THAN_OR_DASH":               151,
}
