package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/weaweawe01/freemarker-ast/internal/tokenspec"
)

func main() {
	var ftlPath string
	var outPath string
	var pkg string
	var prefix string

	flag.StringVar(&ftlPath, "ftl-jj", "", "path to main/javacc/freemarker/core/FTL.jj")
	flag.StringVar(&outPath, "out", "internal/tokenid/generated.go", "output go file path")
	flag.StringVar(&pkg, "pkg", "tokenid", "target package name")
	flag.StringVar(&prefix, "prefix", "TK_", "token const name prefix")
	flag.Parse()

	if ftlPath == "" {
		ftlPath = filepath.Join("..", "main", "javacc", "freemarker", "core", "FTL.jj")
	}

	decls, err := tokenspec.ExtractFromFile(ftlPath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "extract token spec: %v\n", err)
		os.Exit(1)
	}
	ids := tokenspec.AssignIDs(decls)

	src, err := renderSource(pkg, prefix, ids)
	if err != nil {
		fmt.Fprintf(os.Stderr, "render source: %v\n", err)
		os.Exit(1)
	}

	if err := os.MkdirAll(filepath.Dir(outPath), 0o755); err != nil {
		fmt.Fprintf(os.Stderr, "mkdir output dir: %v\n", err)
		os.Exit(1)
	}
	if err := os.WriteFile(outPath, src, 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "write generated file: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("token constants generated\n")
	fmt.Printf("input: %s\n", ftlPath)
	fmt.Printf("output: %s\n", outPath)
	fmt.Printf("count: %d\n", len(ids))
}

func renderSource(pkg string, prefix string, ids []tokenspec.TokenID) ([]byte, error) {
	var b bytes.Buffer
	b.WriteString("// Code generated by fm-token-gen; DO NOT EDIT.\n")
	b.WriteString("\n")
	b.WriteString("package " + pkg + "\n")
	b.WriteString("\n")
	b.WriteString("const (\n")
	for _, id := range ids {
		b.WriteString("\t" + prefix + sanitizeConstName(id.Name) + " = " + fmt.Sprintf("%d", id.ID) + "\n")
	}
	b.WriteString(")\n")
	b.WriteString("\n")

	sorted := append([]tokenspec.TokenID(nil), ids...)
	sort.Slice(sorted, func(i, j int) bool {
		return sorted[i].ID < sorted[j].ID
	})

	b.WriteString("var IDToName = map[int]string{\n")
	for _, id := range sorted {
		b.WriteString("\t" + fmt.Sprintf("%d", id.ID) + ": " + strconvQuote(id.Name) + ",\n")
	}
	b.WriteString("}\n")
	b.WriteString("\n")
	b.WriteString("var NameToID = map[string]int{\n")
	for _, id := range sorted {
		b.WriteString("\t" + strconvQuote(id.Name) + ": " + fmt.Sprintf("%d", id.ID) + ",\n")
	}
	b.WriteString("}\n")

	formatted, err := format.Source(b.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format generated source: %w", err)
	}
	return formatted, nil
}

func sanitizeConstName(name string) string {
	name = strings.TrimSpace(name)
	name = strings.ReplaceAll(name, "-", "_")
	name = strings.ReplaceAll(name, ".", "_")
	name = strings.ReplaceAll(name, " ", "_")
	return name
}

func strconvQuote(s string) string {
	return `"` + strings.ReplaceAll(s, `"`, `\"`) + `"`
}
